edemocracy/ekklesia-portal

scripts/import_proposition_json.py
tests/create_test_db.py

adding JSON import script #2

---

scripts/export_proposition_csv.py

add proposition csv export script #3

---

src/ekklesia_portal/concepts/proposition/proposition_cells.py
src/ekklesia_portal/concepts/proposition/templates/proposition.j2.jade
src/ekklesia_portal/config.example.yml
src/ekklesia_portal/default_settings.py
src/ekklesia_portal/helper/url_shortener.py
src/ekklesia_portal/sass/portal.sass
src/ekklesia_portal/static/css/portal.css
src/ekklesia_portal/translations/de/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/en/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/fr/LC_MESSAGES/messages.po
tests/concepts/proposition/test_proposition_cells.py

added proposition sharing

---

scripts/export_proposition_csv.py
scripts/organize_ballots.py

16 organize ballots

---

src/ekklesia_portal/concepts/proposition/proposition_cells.py
src/ekklesia_portal/concepts/proposition/proposition_contracts.py
src/ekklesia_portal/concepts/proposition/proposition_views.py
src/ekklesia_portal/concepts/proposition/templates/edit_proposition.j2.jade
src/ekklesia_portal/concepts/proposition/templates/proposition_actions.j2.jade
src/ekklesia_portal/translations/de/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/en/LC_MESSAGES/messages.po

added edit button for administrators for propositions; added edit dialog; added German and English title of edit dialog; fixed issue with one missing German text for 'proposition menu'; tested; seems ok; corresponding issue is #5
regards
holger

administrators now can edit propositions

---

python_dev_env.nix
src/ekklesia_portal/concepts/ballot/ballot_contracts.py
src/ekklesia_portal/concepts/proposition/proposition_cells.py
src/ekklesia_portal/concepts/proposition/templates/proposition.j2.jade
src/ekklesia_portal/concepts/proposition/templates/proposition_history_finished.j2.jade
src/ekklesia_portal/concepts/proposition/templates/proposition_history_scheduled.j2.jade
src/ekklesia_portal/concepts/proposition/templates/proposition_history_submitted.j2.jade
src/ekklesia_portal/concepts/proposition/templates/proposition_status_finished.j2.jade
src/ekklesia_portal/concepts/proposition/templates/proposition_status_scheduled.j2.jade
src/ekklesia_portal/concepts/proposition/templates/proposition_status_submitted.j2.jade
src/ekklesia_portal/database/datamodel.py
src/ekklesia_portal/enums.py
src/ekklesia_portal/translations/de/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/en/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/fr/LC_MESSAGES/messages.po
tests/create_test_db.py

* rename proposition status planned to scheduled
* delete votingresult table and add result attribute with type jsonb to ballot
* split proposition template to separate sidebar proposition status template files
* adapt test db for further voting result testing
Closes #18

Implement proposition status support for voting result display

---

scripts/import_voting_result.py
src/ekklesia_portal/concepts/proposition/proposition_cells.py
src/ekklesia_portal/concepts/proposition/templates/proposition_status_finished.j2.jade
src/ekklesia_portal/database/datamodel.py
src/ekklesia_portal/enums.py
src/ekklesia_portal/translations/de/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/en/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/fr/LC_MESSAGES/messages.po
tests/create_test_db.py

* added enum for openslides results
* optimized proposition templates for enum usage
* changed proposition result state declined to rejected
* babel optimizations
* Closes #22

add openslides voting result import script

---

src/ekklesia_portal/concepts/proposition/proposition_views.py

desired redirect implemented

---

src/ekklesia_portal/concepts/proposition/proposition_cells.py
src/ekklesia_portal/concepts/proposition/proposition_contracts.py
src/ekklesia_portal/concepts/proposition/proposition_views.py
src/ekklesia_portal/concepts/proposition/templates/proposition.j2.jade
src/ekklesia_portal/concepts/proposition/templates/proposition_card.j2.jade
src/ekklesia_portal/sass/portal.sass

* moved card-body to own template file
* Closes #19

added proposition highlighting, when supported

---

scripts/import_election_program.py

This adds a script to import a markdown formatted election program
and create propositions for removal of the chapters of the program.
Department, subject area and voting phase can be given through the command line parameters.

Add import election program script to create removal propositions

---

src/ekklesia_portal/concepts/ekklesia_portal/cell/layout.py
src/ekklesia_portal/concepts/ekklesia_portal/templates/layout.j2.jade
src/ekklesia_portal/concepts/proposition/proposition_cells.py
src/ekklesia_portal/concepts/proposition/proposition_views.py
src/ekklesia_portal/concepts/proposition/propositions.py
src/ekklesia_portal/concepts/proposition/templates/propositions.j2.jade
src/ekklesia_portal/sass/portal.sass
src/ekklesia_portal/translations/de/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/en/LC_MESSAGES/messages.po
tests/concepts/proposition/test_propositions.py

- Add filter for voting phase, proposition status, voting phase, department and subject area
- Add tests for these filters
- Display filters with their respective display names over the results
- Add all parameters to the header buttons to be able to sort the results
Resolves #38

Add proposition filters

---

src/ekklesia_portal/concepts/proposition/proposition_cells.py
src/ekklesia_portal/concepts/proposition/propositions.py

- Support quoted words for filters
- Ignore case in filters
Closes #55

Search improvements

---

src/ekklesia_portal/concepts/proposition/proposition_views.py

Fix proposition redirect when proposition is not found

---

src/ekklesia_portal/concepts/proposition/templates/propositions.j2.jade
src/ekklesia_portal/sass/portal.sass

As data URIs must be explicitly allowed with CORS headers, this method is easier.

Use FontAwesome icon instead of svg for dropdown

---

nix/serve_app.nix
scripts/create_db.py

Create an almost empty database for the portal with the following contents:
- An admin group
- A local admin user in this group with the credentials admin:admin
- Temporary values for all customizable texts

Add create db script

---

src/ekklesia_portal/concepts/department/department_cells.py
src/ekklesia_portal/concepts/department/templates/department.j2.jade
src/ekklesia_portal/concepts/proposition/proposition_cells.py
src/ekklesia_portal/concepts/proposition/proposition_views.py
src/ekklesia_portal/concepts/proposition/propositions.py
src/ekklesia_portal/concepts/proposition/templates/new_proposition.j2.jade
src/ekklesia_portal/concepts/proposition/templates/proposition.j2.jade
src/ekklesia_portal/concepts/subject_area/subject_area_cells.py
src/ekklesia_portal/concepts/subject_area/templates/subject_area.j2.jade
src/ekklesia_portal/config.example.yml
src/ekklesia_portal/translations/de/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/en/LC_MESSAGES/messages.po
tests/concepts/proposition/test_propositions.py

- Display number of members of department and subject area
- Move tabs in proposition view to bottom
- Fix discourse importer
- Finish implementation for creation of associated propositions
Some more commits coming soon.

Improvements after a user test

---

src/ekklesia_portal/concepts/proposition/proposition_cells.py
src/ekklesia_portal/concepts/proposition/propositions.py
src/ekklesia_portal/translations/de/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/en/LC_MESSAGES/messages.po

Re-adds the fixes from #111 
This allows to create counter propositions again
@dpausp Or were these features removed intentionally?

Fix counter propositions again

---

src/ekklesia_portal/concepts/proposition/proposition_views.py

Make qualified when:
- Supporter quorum is met when supporting
- Supporter quorum is already met when submitting a draft
Closes #46

Change proposition state to qualified once requirements are met

---

src/ekklesia_portal/concepts/proposition/proposition_cells.py
src/ekklesia_portal/concepts/proposition/proposition_views.py
src/ekklesia_portal/concepts/user/templates/user.j2.jade
src/ekklesia_portal/concepts/user/user_cells.py
src/ekklesia_portal/concepts/user/user_views.py
src/ekklesia_portal/translations/de/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/en/LC_MESSAGES/messages.po

- Join when creating a proposition
- Join when supporting a proposition
- Join when becoming submitter of proposition
- Prevent leaving a subject area when supporting a non-qualified proposition
- Is this enough for status=SUBMITTED or do we need other states, too?

Join subject areas automatically when interacting with propositions

---

nix/docker.nix
src/ekklesia_portal/concepts/voting_phase/templates/edit_voting_phase.j2.jade
src/ekklesia_portal/concepts/voting_phase/voting_phase_cells.py
src/ekklesia_portal/concepts/voting_phase/voting_phase_views.py
src/ekklesia_portal/datamodel.py
src/ekklesia_portal/lib/voting.py
src/ekklesia_portal/lib/vvvote/__init__.py
src/ekklesia_portal/translations/de/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/en/LC_MESSAGES/messages.po
src/ekklesia_portal/voting_modules/__init__.py
src/ekklesia_portal/voting_modules/vvvote.py
tests/concepts/voting_phase/test_voting_phases.py

- I noticed the docker image didn't work anymore, this patch includes a possible fix for this. Does that make sense?
- Adds button to edit voting phase view to retrieve voting results from VVVote
- Retrieves results and updates the ballot's result fields accordingly

Implement retrieving results from vvvote

---

src/ekklesia_portal/app.py
src/ekklesia_portal/concepts/voting_phase/templates/voting_phase.j2.jade
src/ekklesia_portal/concepts/voting_phase/voting_phase_views.py
src/ekklesia_portal/lib/vvvote/election_config.py
src/ekklesia_portal/translations/de/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/en/LC_MESSAGES/messages.po
tests/create_test_db.py
tests/lib/vvvote/test_election_config.py

- Open links to VVVote in new tabs
- Use random order for multiple propositions per ballot
- Use qualification date to order ballots
- Send ballot id and rand part of proposition id to VVVote instead of sequential numbers
- Adapt tests accordingly
Fix create_test_db script
Fix exception on incorrect SSO response

Improve vvvote integration and fix login exception

---

src/ekklesia_portal/app.py
src/ekklesia_portal/concepts/ekklesia_portal/templates/layout.j2.jade
src/ekklesia_portal/concepts/proposition/proposition_cells.py
src/ekklesia_portal/concepts/proposition/proposition_contracts.py
src/ekklesia_portal/concepts/proposition/proposition_views.py
src/ekklesia_portal/concepts/proposition/propositions.py
src/ekklesia_portal/concepts/proposition/templates/history/proposition_history_qualified.j2.jade
src/ekklesia_portal/concepts/proposition/templates/history/proposition_history_scheduled.j2.jade
src/ekklesia_portal/concepts/proposition/templates/history/proposition_history_voting.j2.jade
src/ekklesia_portal/concepts/proposition/templates/propositions.j2.jade
src/ekklesia_portal/concepts/user/templates/user.j2.jade
src/ekklesia_portal/concepts/user/user_cells.py
src/ekklesia_portal/concepts/voting_phase/voting_phase_contracts.py
src/ekklesia_portal/datamodel.py
src/ekklesia_portal/lib/discourse.py
src/ekklesia_portal/translations/de/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/en/LC_MESSAGES/messages.po
src/ekklesia_portal/translations/messages.pot
tests/lib/vvvote/test_election_config.py

This PR includes a lot of fixes and improvements from testing. 
Each fix/feature should be contained in a single commit as well as possible, so we can remove certain commits if necessary.

Various fixes and improvements from testing feedback
